### ISSUE TITLE
Documentation for object types may need to be enhanced.

### ISSUE THREAD

**Issue by gpaulissen** [ogobrecht/ploc#13]
First of all: I am impressed by the functionality for packages. Simple to use.

However I have not been able to generate correct documentation from a more advanced Object Type: 
[02.TYPE_SPEC.DATA_ROW_T.txt](https://github.com/ogobrecht/ploc/files/10509558/02.TYPE_SPEC.DATA_ROW_T.txt)

I have tried of course the /** **/ above or below methods but I am not able to get an overall description and a description for each method.

**Comment by ogobrecht** [comment]
Thank you for reporting this and the provided example. I need to have a deeper look at the weekend. Will come back to you...

**Comment by ogobrecht** [comment]
I had a look at it. Need to rework the regex for it. This will take a little bit longer as I have not so much free time at the moment and I need to take care of not to break existing functionality. Will come back to you when I have something to share.

**Comment by ogobrecht** [comment]
Hi Gert-Jan. Sorry, I totally forgot to work further on this. I got a pull request for a different topic and saw your issue again. I had already worked on it over a year ago. I will try to fix it next weekend. 

Best regards 
Ottmar

**Comment by ogobrecht** [comment]
Hi Gert-Jan. The new version 0.9.0 is published on npmjs.com. Can you please test, if it works now ok for you?

If you encounter issues, please reopen this thread here. Thank you again for your feedback and sorry, that this took so long.

Best regards
Ottmar
